CREATE TABLE IF NOT EXISTS messages
(
    id   VARCHAR(60) DEFAULT RANDOM_UUID() PRIMARY KEY,
    text VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS projects
(
    id   VARCHAR(60) DEFAULT RANDOM_UUID() PRIMARY KEY,
    name VARCHAR NOT NULL,
    date_created DATE DEFAULT CURRENT_DATE() CONSTRAINT REQUIRED_DATE NOT NULL
--     CONSTRAINT date_created DEFAULT CURRENT_DATE()
);